const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const code = fs.readFileSync('public-data-dashboard/src/analysisHelpers.js', 'utf8');
const context = { window: {} };
vm.createContext(context);
vm.runInContext(code, context);
const h = context.window.PublicDataDashboard.AnalysisHelpers;
assert(h.deriveFallbackKeyword('서울 부동산 가격 데이터 보여줘').includes('서울'));
assert(!['데이터', '보여줘'].includes(h.deriveFallbackKeyword('서울 부동산 가격 데이터 보여줘')));
const dataset = { title: '서울 부동산 실거래가', provider: '서울시' };
const resource = { name: '실거래 CSV', format: 'CSV', url: 'https://example.com/a.csv', is_previewable: true, is_visualizable: true };
const preview = { preview: { kind: 'table', headers: ['지역','가격'], rows: [['강남', '10'], ['마포', '7']] }, metadata: { content_type: 'text/csv', bytes_read: 128 } };
const visualization = { chart_type: 'bar', labels: ['강남','마포'], datasets: [{ label: '가격', data: [10, 7] }], metadata: { source_url: 'https://example.com/a.csv', resource_format: 'CSV', content_type: 'text/csv', bytes_read: 128 } };
const baseOutline = h.deriveAnalysisOutline({ prompt: '서울 부동산', keyword: '서울 부동산', dataset, resource });
const richerOutline = h.deriveAnalysisOutline({ prompt: '서울 부동산', keyword: '서울 부동산', dataset, resource, resourcePreview: preview, visualization, additionalPrompt: '강남만 비교' });
assert.notDeepStrictEqual(baseOutline, richerOutline);
const comments = h.deriveDataComment({ prompt: '서울 부동산', keyword: '서울 부동산', dataset, resource, resourcePreview: preview, visualization, additionalPrompt: '강남만 비교' }).join('\n');
assert(comments.includes('최대값'));
assert(comments.includes('preview'));
assert(comments.includes('강남만 비교'));
console.log('frontend analysis helper checks passed');
